version: "2"

services:
  kogsback:
    build: ./backend/
    volumes:
      - ./backend/src:/backend
    ports:
      - "1337:1337"

  kogsfront:
    build: ./frontend/
    volumes:
      - ./frontend/src:/usr/share/nginx/html
    ports:
      - "80:80"      